export const RECIPES = [
  {
    id: 0,
    title: "Nice Dinner",
    menu: "Menu 1",
    image: "/assets/images/menu1.jpg",
    featured: true,
    time: 30,
    difficulty: "Low",
    ingredients: "Apple",
    foodType: "Vegan",
    introduction: "Very easy and nice menu for a special day",
    description:
      "pqiuwl.dk 23985. kjdlkfjasdiudf dlkjseiwl alksdf dlkwo slkdflw dkjsdas. ;laksdjfow. dlkjsoeijfsldkjfaspj ldkjsodi kdjfasdoifwl dkfjsl jfweoijfslkd j dlkfajsdofji wlkejf  dfsj lakdjfpa ",
  },
  {
    id: 1,
    title: "Nice Salad",
    menu: "Menu 2",
    image: "/assets/images/menu2.jpg",
    featured: true,
    time: 45,
    difficulty: "High",
    ingredients: "Beef",
    foodType: "Diabetic vegan",
    introduction: "Very easy and nice menu for a special day",
    description:
      "wlek dkdjiwju2l dkjsn.ak dijkfjdk .dkjasfo dk jkdowkjd lk  oiwlskj.",
  },
  {
    id: 2,
    title: "Nice Snack",
    menu: "Menu 3",
    image: "/assets/images/menu3.jpg",
    featured: true,
    time: 55,
    difficulty: "Medium",
    ingredients: "Carrot",
    foodType: "Gluten Free",
    introduction: "Very easy and nice menu for a special day",
    description: "easerasedf ldkja dkfjask kdjslkk dkowiend kjksji kdslkwl.",
  },
  {
    id: 3,
    title: "Gorgeous Dinner",
    menu: "Menu 4",
    image: "/assets/images/menu4.jpg",
    featured: true,
    time: 15,
    difficulty: "Medium",
    ingredients: "Root Beat",
    foodType: "Vegan",
    introduction: "Very easy and nice menu for a special day",
    description:
      "easerasedf easerasedf ldkja easerasedf ldkja dkfjask kdjslkk dkowiend kjksji kdslkwldkfjask kdjslkk dkowiend kjksji kdslkwlldkja dkfjask kdjslkk dkowiend kjksji kdslkwl.",
  },
  {
    id: 4,
    title: "Pretty Challenging but Worth it!",
    menu: "Menu 5",
    image: "/assets/images/menu5.jpg",
    featured: true,
    time: 15,
    difficulty: "High",
    ingredients: "Onion",
    foodType: "Vegan, Gluten Free",
    introduction: "Very easy and nice menu for a special day",
    description:
      "Hello this is Nathan Jeon and I am writing code for my project. ",
  },
];
