export const RECIPES = [
  {
    id: 0,
    title: "Nice Dinner",
    menu: "Vegan Apple Steak",
    image: "../assets/menu1.jpg",
    featured: true,
    time: 30,
    difficulty: "Low",
    ingredients: "Apple",
    foodType: "Vegan",
    introduction: "Very easy for a special day",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 1,
    title: "Nice Salad",
    menu: "Beef Steak Salad",
    image: "../assets/menu2.jpg",
    featured: true,
    time: 45,
    difficulty: "High",
    ingredients: "Beef",
    foodType: "Diabetic",
    introduction: "Very nice menu for a special day",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 2,
    title: "Nice Snack",
    menu: "Fried Carrot",
    image: "../assets/menu3.jpg",
    featured: true,
    time: 55,
    difficulty: "Medium",
    ingredients: "Carrot",
    foodType: "Gluten Free",
    introduction: "Easy and nice menu for a special day",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 3,
    title: "Gorgeous Dinner",
    menu: "Beat Yogurt Salad",
    image: "../assets/menu4.jpg",
    featured: true,
    time: 15,
    difficulty: "Medium",
    ingredients: "Root Beat",
    foodType: "Vegan",
    introduction: "Very nice menu for a special day",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 4,
    title: "Pretty Challenging but Worth it!",
    menu: "Onion Steak with Crumbles",
    image: "../assets/menu5.jpg",
    featured: true,
    time: 15,
    difficulty: "High",
    ingredients: "Onion",
    foodType: "Vegan, Gluten Free",
    introduction: "Very easy and nice menu for a special day",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
